# Generated by Django 5.1.3 on 2024-11-12 07:27

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BankLoanDB',
            fields=[
                ('name', models.CharField(max_length=20)),
                ('loanID', models.IntegerField(primary_key='True', serialize=False)),
                ('accNo', models.IntegerField()),
                ('occupation', models.CharField(max_length=20)),
                ('collateral', models.CharField(max_length=30)),
            ],
        ),
    ]
